Controllers/AdminController.cs
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;

namespace Lab3_LeChiCuong_2131200001.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult UserTable()
        {
            return View();
        }

        public IActionResult BookManagement()
        {
            return View();
        }
    }
}

Controllers/AuthenticateController.cs
using Microsoft.AspNetCore.Mvc;

namespace Lab3_LeChiCuong_2131200001.Controllers
{
    public class AuthenticateController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Register()
        {
            return View();
        }
    }
}

Controllers/BookController.cs
using System.Threading.Tasks;
using Lab3_LeChiCuong_2131200001.Data;
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace Lab3_LeChiCuong_2131200001.Controllers
{
    public class BookController : Controller
    {

        private readonly AppDbContext _context;

        private readonly IWebHostEnvironment _env;

        public BookController(AppDbContext context, IWebHostEnvironment env)
        {

            _context = context;
            _env = env;

        }

        public async Task<IActionResult> Index([FromQuery] string bookCode)
        {
            Console.WriteLine("Code: " + bookCode);
            var book = await _context.Books
                .Include(book => book.Categories)
                .FirstOrDefaultAsync(book => book.BookCode == bookCode);
            return View(book);
        }

        public async Task<IActionResult> PageProgrammingBook()
        {

            var books = await _context.Books
                  .Include(category => category.Categories)
                  .Where(book => book.Categories.Any(cate => cate.Name == "Programming"))
               .ToListAsync();
            return View(books);
        }

        public async Task<IActionResult> PageFictionBook()
        {

            var books = await _context.Books
                  .Include(category => category.Categories)
                  .Where(book => book.Categories.Any(cate => cate.Name == "Fiction"))
               .ToListAsync();
            return View(books);
        }

        public async Task<IActionResult> ViewPDF([FromQuery] string bookCode)
        {

            var book = await _context.Books
                .Include(book => book.Categories)
                .FirstOrDefaultAsync(book => book.BookCode == bookCode);

            if (book == null)
            {
                ViewBag.Error = true;
                ViewBag.ErrorMessage = "PDF path does not exist";
            }
            else
            {
                if (!System.IO.File.Exists(_env.WebRootPath + "/assets/pdf/" + book.Pdf))
                {
                    ViewBag.Error = true;
                    ViewBag.ErrorMessage = "PDF path does not exist";
                } else
                {
                    ViewBag.Error = false;
                }
            }
            return View(book);
        }

    }
}

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <style>
        .sidebar {
			border-right: 1px solid #dee2e6;
        }

        .content {
            min-height: calc(100vh - 140px); /* Adjust based on header/footer height */
			padding: 0;
        }

		.navbar {
			border-bottom: 1px solid #dee2e6;
		}

		footer {
			border-top: 1px solid #dee2e6;
			padding: 10px 0;
		}

    </style>
</head>
<body>
    <header class="navbar bg-white">
        <div class="container-fluid">
            <a class="navbar-brand">
                <img class="mb-1" style="cursor: pointer" src="/assets/image/logo.6362708d.svg" loading="lazy" />
            </a>
            <div class="">
                <img src="/assets/image/profile.jpg" class="rounded-circle" width="32" height="32" alt="Profile">
            </div>
        </div>
    </header>

    <div class="container-fluid">
        <div class="row">
            <div class="col-2 sidebar bg-white">
                <ul class="menuDashboard">
					@* <li class="menuItemDashboard"> *@
					@* 	<a class="nav-link" asp-controller="Admin" asp-action="Index">Dashboard</a> *@
					@* </li> *@
                    <li class="menuItemDashboard">
						<a class="nav-link" asp-controller="Admin" asp-action="UserTable">User Management</a>
					</li>
                    <li class="menuItemDashboard">
						<a class="nav-link" asp-controller="Admin" asp-action="BookManagement">Book Management</a>
					</li>
                </ul>
            </div>

            <div class="col-10 bg-light content">
                <div class="">@RenderBody()</div>
            </div>
        </div>
        <footer class="bg-white">
            <div class="container-fluid">
                <div class="text-center">Footer</div>
            </div>
        </footer>
    </div>

    
</body>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Lab3_LeChiCuong_2131200001</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/Lab3_LeChiCuong_2131200001.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav>
			@* <div class="container-fluid"> *@
			<div class="container">
				<div class="row">
					<div class="col-12 d-flex justify-content-end">
						<p class="text-dark" style="width: fit-content">
							<a class="text-decoration-none text-black" asp-controller="Authenticate" asp-action="Register" style="cursor: pointer">Đăng ký</a> |
							<a class="text-decoration-none text-black" asp-controller="Authenticate" asp-action="Login" style="cursor: pointer">Đăng nhập</a>
						</p>
					</div>
				</div>
				<div class="row">
					<div class="col-3">
						<a asp-controller="Home" asp-action="Index">
							<img class="mb-1" style="cursor: pointer" src="/assets/image/logo.6362708d.svg" loading="lazy" />
						</a>
					</div>
					<div class="col-9">
						<div class="d-flex justify-content-end align-items-center" style="height: 100%">
							<form class="d-flex h-75">
								<input class="form-control me-2" type="search" placeholder="Tìm kiếm...">
								<button class="btn btn-outline-light text-dark" type="submit">Tìm</button>
							</form>
						</div>
					</div>
				</div>

			</div>
			<div style="background-color: #078E15">
				<div class="container">
					<div class="row">
						<div class="col-4">
						</div>
						<div class="col-8">
							<ul class="navbar-nav flex-grow-1 flex-row gap-1 justify-content-end">
								<li class="nav-item px-3 py-1 menuItem">
									<a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Trang chủ</a>
								</li>
								<li class="nav-item px-3 py-1 menuItem">
									<a class="nav-link text-white" asp-area="" asp-controller="Book" asp-action="PageProgrammingBook">Programming</a>
								</li>
								<li class="nav-item px-3 py-1 menuItem">
									<a class="nav-link text-white" asp-area="" asp-controller="Book" asp-action="PageFictionBook">Fiction</a>
								</li>
								<li class="nav-item px-3 py-1 menuItem">
									<a class="nav-link text-white" asp-area="" asp-controller="Admin" asp-action="UserTable">Dashboard</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			@* </div> *@
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top">
		<div class="container mt-2">
			<div class="row">
				<div class="col-3">
					<img src="/assets/image/logo.6362708d.svg" loading="lazy" />
				</div>
				<div class="col-9">
					<ul>
						<li>Full name: Lê Chí Cường</li>
						<li>Class: Practice group 2</li>
					</ul>
				</div>
			</div>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>